### ISSUE TITLE
Allow Users to Edit Slur Words in Hidden Words for Thread UI on uli-website

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/Uli#381]
**Is your feature request related to a problem? Please describe.**
A user should be able to edit words in the text box at **Hidden Words for Thread** in the `uli-website` - https://uli.tattle.co.in/hidden-words-for-thread/

What is the **Hidden Words for Thread**?
Meta's Thread now allows you to filter out words that you don't want to see on your feed. Uli's slur list can assist you in adding a list of slurs in Indian languages. If you are being targeted or abused on social media in Indian languages, consider adding these words to your list of "hidden words" on Thread.
Users can filter and copy words from Uli's Hidden Words for Thread and directly paste them on the Hidden List in Instagram or Twitter. 

A user should also be able to edit the slur list on the website UI, as it might happen that a user doesn't want all the slur words in their hidden list. 

**Describe the solution you'd like**
A user should be able to **Edit** and **Delete** some slur words in the text box area in the UI itself.

**Comment by Drex72** [comment]
Hey @aatmanvaidya  So i started working on this issue, by the way i would love it if you would assign this isssue to me
but there are some things i need to have clarification on

**Comment by aatmanvaidya** [comment]
Hi @Drex72, let me know where you need clarification on

**Comment by aatmanvaidya** [comment]
Hi @Drex72 , this issue has been resolved by another contributor. 

Thank you for your time and effort in attempting to address it, please feel free to explore and take up other issues.

**Comment by Drex72** [comment]
> Hi @Drex72 , this issue has been resolved by another contributor.
> 
> Thank you for your time and effort in attempting to address it, please feel free to explore and take up other issues.

So i looked at the pr and the issue i was trying to handle was why i didnt solve and it hasn't been resolved in this  pr either
let me send you a screen recording

it might not be a valid issue, but let me know what you think

https://github.com/tattle-made/Uli/assets/90635055/f80e933d-7028-49e2-a96b-6719eadc63a6

**Comment by aatmanvaidya** [comment]
Hi @Drex72 
We want it that way, Currently, there are no REST APIs connected to the back end or the database, which is why when you refresh the page or click on a different language, all the slurs return to their original state.

As written in the description of the issue - the primary objective is to allow users to easily copy and paste slur words crowdsourced by Uli to various social media platforms' hidden words lists. However, we wanted to make it flexible for users who might not want specific words. In such cases, users can conveniently edit these words directly on the Uli website's front end and then copy and paste the modified list onto their respective social media accounts. We created this issue with this in mind. 

hope that makes sense
